# Generated by Django 4.2 on 2023-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
