# Generated by Django 4.2 on 2023-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
