# Generated by Django 4.2 on 2023-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0004_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="type_of_wallet",
            field=models.CharField(
                choices=[("VISA", "Visa"), ("MASTER_CARD", "Mastercard")], max_length=15
            ),
        ),
    ]
