# Generated by Django 4.2 on 2023-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0005_alter_wallet_type_of_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("EUR", "EUR"), ("RUB", "RUB")], max_length=4
            ),
        ),
    ]
