# Generated by Django 4.2 on 2023-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0007_delete_currency_delete_typeofwalet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
