# Generated by Django 4.2 on 2023-04-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0010_alter_wallet_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
