# Generated by Django 4.2 on 2023-04-04 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0011_wallet_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="count",
        ),
    ]
