# Generated by Django 4.2 on 2023-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0013_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
    ]
