# Generated by Django 4.2 on 2023-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transfer_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
