# Generated by Django 4.2 on 2023-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_transaction_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "PAID"), ("FAILED", "FAILED")], max_length=25
            ),
        ),
    ]
