# Generated by Django 4.2 on 2023-04-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "PAID"), ("FAILED", "FAILED")],
                editable=False,
                max_length=25,
            ),
        ),
    ]
